### ISSUE TITLE
Unpublish ejson

### ISSUE THREAD

**Issue by ForbesLindesay** [tj/eson#14]
At the moment you seem to have ejson and eson (this module) in npm.  Can you unpublish ejson please as it doesn't look like it's actually used?

**Comment by tj** [comment]
hmm yea that's lame, might break people's shit though, joys of global namespace

**Comment by 3rd-Eden** [comment]
i'll be more than happy to replace the current ejson package name with https://github.com/primus/EJSON if you ever choose to release it ;-) which is a parser/encoder for the ejson format that meteor uses which also handles dates and array's correctly.

**Comment by tj** [comment]
@3rd-Eden what's your npm username (gah npm is annoying) I'll just add you and you can publish a version higher so it doesn't break anything

**Comment by ForbesLindesay** [comment]
@visionmedia Awesome, exactly what I was about to suggest.

@3rd-Eden thanks for doing exactly what I was about to do myself

**Comment by 3rd-Eden** [comment]
It’s V1 (uppercase) And yea, i’ll major bump it.

**Comment by tj** [comment]
done!

**Comment by ForbesLindesay** [comment]
Awesome, thanks all
