### ISSUE TITLE
Ability to parse objects in addition to JSON

### ISSUE THREAD

**Issue by 3rd-Eden** [tj/eson#6]
As most of my configuration objects are plain JavaScript object's that are required using `require('file.json')` which already parses the content to JSON.

**Comment by tj** [comment]
+1, I use .read() but ya i agree there's no good reason we shouldn't be able to pass an object to .parse(), though it currently works off of the JSON.parse reviver function

**Comment by 3rd-Eden** [comment]
I'm currently just doing a `JSON.stringify` on my object and send it to `eson`. Which isn't the most pretty way of doing things, but it get the job done.

Parsing objects wouldn't be to hard to add, as long we don't hit any recursion.

**Comment by tj** [comment]
for now we could just .stringify in .parse() so it's at least encapsulated and then if we need better perf fix it later. I only use it for config files right now so that part definitely doesn't matter to me ATM

**Comment by 3rd-Eden** [comment]
I'll prepare a pull request and some tests for it
